# Site settings
title: 他喵的老師筆記
email: filitov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  他喵的老師偶爾也是會寫寫筆記
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: filitov
github_username:  Filitov

# Build settings
markdown: kramdown
